# Generated by Django 3.1.7 on 2021-07-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=99)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('-1', 'pending'), ('1', 'done')], default='-1', max_length=100)),
            ],
        ),
    ]
