# Generated by Django 3.1.7 on 2021-07-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('done', 'done')], default='pending', max_length=100),
        ),
    ]
