apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-all-deployment
spec:
  selector:
    matchLabels:
      app: django
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: abhitrone/django:1.1
        ports:
        - containerPort: 8000
        env:
        - name: HOST_IP
          value: 192.168.64.2
---
apiVersion: v1
kind: Service
metadata:
  name: django-all-service
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: django
