---
- hosts: all
  tasks:
    - name: find docker file 
      find:
        path: ~/abhishek/git/django-todo-app
        file_type: file
        patterns: "Dockerfile"
      register: docker_file
      failed_when: docker_file.matched != 1
    
    - debug:
        msg: "{{docker_file}}"

    - name: find shell script to create new docker image
      find:
        path: ~/abhishek/git/django-todo-app
        file_type: file
        patterns: create_new_dockerImage.sh
      register: createDockerImage_shell_script
      when: docker_file.matched == 1 

    - debug:
      #msg: "{{createDockerImage_shell_script}}"
        msg: "{{createDockerImage_shell_script.files[0].path}}"

    - name: create docker image 
      shell: bash "{{createDockerImage_shell_script.files[0].path}}"
      when: createDockerImage_shell_script.matched == 1
      register: image_build_result

    - debug:
        msg: "{{image_build_result}}"
    
