#create a service account tiller for the Tiller server in the kube-system namespace
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: tiller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: 
  name: tiller
#bind the cluster admin role to the above service account. Since we want Tiller to manage resources in all namespaces, we will use ClusteriRoleBinding
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: tiller
    namespace: kube-system
#kubectl apply -f helm-rbac.yml
